version: '2'
services:
  zcash:
    build:
      context: ./zcash-client
    mem_limit: 2000M
    cpu_quota: 30000
    volumes:
      - "/crypto/zcash-analysis-19733/data/.zcash:/root/.zcash"
    ports:
    - "8331:8331"
    - "8332:8332"
    tty: true
    container_name: zcash
  research:
    build:
      context: ./research
    tty: true
    container_name: research
    volumes:
      - "/crypto/zcash-analysis-19733/data/research:/root/research"
  zcashpostgres:
    build:
      context: ./zcashpostgres
    mem_limit: 1000M
    cpu_quota: 40000
    volumes:
      - "/crypto/zcash-analysis-19733/data/pgdata:/var/run/postgresql/data/pgdata"
      - "/crypto/zcash-analysis-19733/data/research:/root/research"
    ports:
    - "8001:5432"
    container_name: zcashpostgres

